### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by cfaha** [lyhlyhl/yys_mouse_click#1]
![image](https://user-images.githubusercontent.com/59524038/101144937-05f49580-3654-11eb-9fe0-c63a769b98d9.png)
会显示这个问题

**Comment by lyhlyhl** [comment]
目前我还在增加功能阶段，我的main函数放在Myui这个文件里，不在main.py内

**Comment by lyhlyhl** [comment]
已经完成了修复，可以拉取最新的版本
