### ISSUE TITLE
q

### ISSUE THREAD

**Issue by Marea-qq** [lyhlyhl/yys_mouse_click#3]
大佬是直接用沙盒+桌面端安全还是用模拟器安全？而且坐标点击的话容不容易被检测awa

**Comment by lyhlyhl** [comment]
模拟器安全哈哈哈，我这个是桌面版 我懒得弄了。坐标点击其实问题不大，可以用找对应图片的方式点击，我看了一些脚本都是这个思路，我也在往那个方向发展。检测的话其实别连续一直刷，都不太容易被检测到

**Comment by Marea-qq** [comment]
好的大佬

**Comment by a-flying-crow** [comment]
模拟器的话似乎会显示句柄有误；我用的雷电模拟器

**Comment by lyhlyhl** [comment]
是的，我的程序只能用桌面版适配的是桌面版，模拟器目前还没开发hhh得慢慢来

**Comment by a-flying-crow** [comment]
好的，辛苦大佬了
