### ISSUE TITLE
无法点击

### ISSUE THREAD

**Issue by mrpeanutzmz** [lyhlyhl/yys_mouse_click#5]
鼠标只移动到了对应位置没有点击

**Comment by lyhlyhl** [comment]
检查一下是否以管理员身份启动

**Comment by mrpeanutzmz** [comment]
> 检查一下是否以管理员身份启动

emm我一开始是用idle运行的
改用打包好的以管理员身份启动就行了

**Comment by lyhlyhl** [comment]
恩，IDE启动的话，其实你把IDE也用管理员启动就可以了，冲冲冲！

**Comment by mrpeanutzmz** [comment]
py小白是这样的了(⊙﹏⊙)
