### ISSUE TITLE
双人御魂，点击开始偶尔会点到窗口边框

### ISSUE THREAD

**Issue by ethuh** [lyhlyhl/yys_mouse_click#6]
点到窗口边框之后，这一轮会开启失败，等于空掉了一轮的时间，消耗了一局御魂时长的BUFF，虽然不出货，但是老心痛了🐶

**Comment by lyhlyhl** [comment]
hahhhh，新版的代码逻辑修复了这个问题。但是由于分辨率没写，所以还没发布。最近摸鱼了嘿嘿嘿

**Comment by ethuh** [comment]
> hahhhh，新版的代码逻辑修复了这个问题。但是由于分辨率没写，所以还没发布。最近摸鱼了嘿嘿嘿

翘首以盼适配不同分辨率和缩放百分比问题，然后还有就是模拟器的适配，大佬加油哇，多护发护发。💕

不过倒也不急，现在使用没啥问题，见过了太多开发的大佬，因为占据了过多平时时间最后弃坑，还是随缘点好，嘿嘿

**Comment by lyhlyhl** [comment]
主要是最近阴阳师老抽不到好东西，然后没啥激情玩阴阳师->没啥激情开发hahhh

**Comment by lyhlyhl** [comment]
> 发布新版本啦，快试试，如果可以的话，可以给点建议哦

**Comment by ethuh** [comment]
> 

已经在下载了，哈哈哈，火速了，居然第二天就更新了，太牛了

**Comment by lyhlyhl** [comment]
哈哈哈哈哈，没有没有，很多之前写好了。但是总担心自己哪里有bug，就一直没发布，然后稍微测试了一下，完善了分辨率啥的。这一版体验绝对比上一版好很多hhahh，因为基本不可能出现乱点的情况==不会有鬼使hei

**Comment by clggwater** [comment]
> 哈哈哈哈哈，没有没有，很多之前写好了。但是总担心自己哪里有bug，就一直没发布，然后稍微测试了一下，完善了分辨率啥的。这一版体验绝对比上一版好很多hhahh，因为基本不可能出现乱点的情况==不会有鬼使hei

好像有问题，我魂土双开，句柄都对，然后也默认邀请了，点击开始之后，窗口自动适配没问题，但是指针不点击，然后就报错了，我截图你看看
![image](https://user-images.githubusercontent.com/23073985/156979877-4693fc61-0906-42d9-9bb0-c634da905f36.png)

**Comment by lyhlyhl** [comment]
啊这是我加的机制，找不到点击按钮了，加个qq？我测试一下置信度调多少合适

**Comment by ethuh** [comment]
> 啊这是我加的机制，找不到点击按钮了，加个qq？我测试一下置信度调多少合适

直接发这里吗？有没有私聊功能？

**Comment by lyhlyhl** [comment]
lyhlyhl@qq.com 你邮件发我吧，好像github无私聊功能

**Comment by ethuh** [comment]
> [lyhlyhl@qq.com](mailto:lyhlyhl@qq.com) 你邮件发我吧，好像github无私聊功能

2333，我居然翻你资料界面率先发出了邮件，才看到你回复让我邮件你

**Comment by lyhlyhl** [comment]
QAQ我好像没法加你，你加我吧，我回你邮件了

**Comment by xingxingxing1** [comment]
双开挖第一局后出现几个字：组队出现异常。不知道咋了，试了几盘，都会出现这句话😭😭

**Comment by lyhlyhl** [comment]
> 
不好意思现在才看到，您这边发邮件给我一下您具体的联系方式，我来具体看一下，后面的版本管理有点乱，这个是我特地加的功能，防止乱点的

**Comment by lyhlyhl** [comment]
> 双开挖第一局后出现几个字：组队出现异常。不知道咋了，试了几盘，都会出现这句话😭😭

不好意思现在才看到，您这边发邮件给我一下您具体的联系方式，我来具体看一下，后面的版本管理有点乱，这个是我特地加的功能，防止乱点的
